on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
name: 🚀 Nahrať na FTP
jobs:
  web-deploy:
    name: 🚀 Nahrať na FTP server - STAVKY
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout repozitára
        uses: actions/checkout@v2

      - name: Použiť Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔨 NPM RUN BUILD
        run: |
          npm install --force
          npm run build:forex

      - name: 📂 NAHRAŤ NA FTP SERVER
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: stavkoveporadenstvo.sk
          username: ftp.stavkoveporadenstvo.sk
          password: Wy1=?6T^0B
          local-dir: ./client/build
          server-dir: stavkoveporadenstvo.sk/web/
          port: 21
          protocol: ftp
          timeout: 1000000
